apiVersion: v1
kind: Service
metadata:
  namespace: prova
  name: simpleapp-svc
  labels:
    name: simpleapp-svc
    app: simpleapp
spec:
  ports:
  - port: 8008
    protocol: TCP
    targetPort: 8008
  selector:
    app: simpleapp
status:
  loadBalancer: {}