apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prova
  name: simpleapp
  labels:
    app: simpleapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
        - name: simpleapp-python
          image: marcosrossem/simple-app-python
          imagePullPolicy: Always
          ports:
            - containerPort: 8008
          envFrom:
          - configMapRef:
              name: simpleapp-cm

          #livenessProbe:
           # httpGet:
            #  path: /health
             # port: 8008
            #initialDelaySeconds: 5
            #periodSeconds: 3
            
         # readinessProbe:
          #  httpGet:
           #   path: /health
            #  port: 8008
            #initialDelaySeconds: 5
            #periodSeconds: 3
