apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: atp-elk
spec:
  version: 7.12.0
  nodeSets:
  - name: elastic
    count: 1
    config:
      node.store.allow_mmap: false
